# Calamares main configuration for ShobikaOs

modules-search: [ /usr/share/calamares/modules, /etc/calamares/modules ]

instances:
  - id:       partition
    module:   partition
    config:   partition.conf
  - id:       packagechooser
    module:   packagechooser
    config:   packagechooser.conf

sequence:
  - show welcome
  - show locale
  - show keyboard
  - show partition
  - show packagechooser
  - show users
  - show bootloader
  - exec partition
  - exec mount
  - exec packagechooser
  - exec unpackfs
  - exec shellprocess
  - exec users
  - exec fstab
  - exec localecfg
  - exec bootloader
  - show finished

branding: shobikaos
